package it.polimi.ingsw.bean.action;

import java.io.Serializable;
import java.util.Objects;

/**
 * Actions are messages generated by the client to communicate to the server.
 * Each one represent a user's move, for this every action have the variable Nickname.
 * Action is a abstract class extended by many classes.
 * Since the actions are sent on the sockets they implement Serializable.
 *
 * @see Serializable
 */
public abstract class Action implements Serializable {

    /**
     * The player's nickname who generated the action
     */
    protected final String nickname;

    /**
     * Default constructor
     * @param nickname The player's nickname who generate the action
     */
    public Action(String nickname) {
        this.nickname = nickname;
    }

    public String getNickname() {
        return nickname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Action)) return false;
        Action action = (Action) o;
        return Objects.equals(nickname, action.nickname);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nickname);
    }
}
